security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        token:
            pattern:    ^/token
            security:   false

        api:
            pattern:    ^/api(?!/lectures/\d+/render_form)
            fos_oauth:  true
            stateless:  true
            anonymous:  false

    access_control:
        - { path: ^/, roles: [ IS_AUTHENTICATED_FULLY ] }
