category_create:
    path: /{id}
    methods: POST
    defaults: { _controller: "AppBundle:Category:create", id: null }

category_read:
    path: /{id}/{sublist}
    methods: GET
    defaults: { _controller: "AppBundle:Category:read", id: null, sublist: null }

category_update:
    path: /{id}
    methods: PUT
    defaults: { _controller: "AppBundle:Category:update", id: null }

category_delete:
    path: /{id}
    methods: DELETE
    defaults: { _controller: "AppBundle:Category:delete", id: null }
