category_create:
    path: /
    methods: POST
    defaults: { _controller: "AppBundle:Category:create" }

category_read:
    path: /{id}
    methods: GET
    defaults: { _controller: "AppBundle:Category:read" }

category_update:
    path: /{id}
    methods: PUT
    defaults: { _controller: "AppBundle:Category:update" }

category_delete:
    path: /{id}
    methods: DELETE
    defaults: { _controller: "AppBundle:Category:delete" }
