event_create:
    path: /create
    defaults: { _controller: "AppBundle:Event:create" }

event_read:
    path: /read/{id}
    defaults: { _controller: "AppBundle:Event:read" }

event_update:
    path: /update/{id}
    defaults: { _controller: "AppBundle:Event:update" }

event_delete:
    path: /delete/{id}
    defaults: { _controller: "AppBundle:Event:delete" }
