event_create:
    path: /
    methods: POST
    defaults: { _controller: "AppBundle:Event:create" }

event_read:
    path: /{id}
    methods: GET
    defaults: { _controller: "AppBundle:Event:read" }

event_update:
    path: /{id}
    methods: PUT
    defaults: { _controller: "AppBundle:Event:update" }

event_delete:
    path: /{id}
    methods: DELETE
    defaults: { _controller: "AppBundle:Event:delete" }
