form_create:
    path: /
    methods: POST
    defaults: { _controller: "AppBundle:Form:create" }

form_read:
    path: /{id}
    methods: GET
    defaults: { _controller: "AppBundle:Form:read" }

form_update:
    path: /{id}
    methods: PUT
    defaults: { _controller: "AppBundle:Form:update" }

form_delete:
    path: /{id}
    methods: DELETE
    defaults: { _controller: "AppBundle:Form:delete" }
