lecture_create:
    path: /
    methods: POST
    defaults: { _controller: "AppBundle:Lecture:create" }

lecture_read:
    path: /{id}
    methods: GET
    defaults: { _controller: "AppBundle:Lecture:read" }

lecture_update:
    path: /{id}
    methods: PUT
    defaults: { _controller: "AppBundle:Lecture:update" }

lecture_delete:
    path: /{id}
    methods: DELETE
    defaults: { _controller: "AppBundle:Lecture:delete" }
