lecture_create:
    path: /{id}
    methods: POST
    defaults: { _controller: "AppBundle:Lecture:create", id: null }

lecture_render:
    path: /{id}/render_form
    methods: GET
    defaults: { _controller: "AppBundle:Lecture:renderForm" }

lecture_read:
    path: /{id}/{sublist}
    methods: GET
    defaults: { _controller: "AppBundle:Lecture:read", id: null, sublist: null }

lecture_update:
    path: /{id}
    methods: PUT
    defaults: { _controller: "AppBundle:Lecture:update", id: null }

lecture_delete:
    path: /{id}
    methods: DELETE
    defaults: { _controller: "AppBundle:Lecture:delete", id: null }
