registration_create:
    path: /
    methods: POST
    defaults: { _controller: "AppBundle:Registration:create" }

registration_read:
    path: /{id}
    methods: GET
    defaults: { _controller: "AppBundle:Registration:read" }
