registration_create:
    path: /{id}
    methods: POST
    defaults: { _controller: "AppBundle:Registration:create", id: null }

registration_read:
    path: /{id}/{sublist}
    methods: GET
    defaults: { _controller: "AppBundle:Registration:read", id: null, sublist: null }
