user_create:
    path: /create
    defaults: { _controller: "AppBundle:User:create" }

user_read:
    path: /read/{id}
    defaults: { _controller: "AppBundle:User:read" }

user_update:
    path: /update/{id}
    defaults: { _controller: "AppBundle:User:update" }

user_delete:
    path: /delete/{id}
    defaults: { _controller: "AppBundle:User:delete" }
