user_create:
    path: /
    methods: POST
    defaults: { _controller: "AppBundle:User:create" }

user_read:
    path: /{id}
    methods: GET
    defaults: { _controller: "AppBundle:User:read" }

user_update:
    path: /{id}
    methods: PUT
    defaults: { _controller: "AppBundle:User:update" }

user_delete:
    path: /{id}
    methods: DELETE
    defaults: { _controller: "AppBundle:User:delete" }
