api:
    resource: '@AppBundle/Resources/config/routing/api.yml'
    prefix:   /api

fos_oauth_server_token:
    path: /token
    methods: [GET, POST]
    defaults: { _controller: "AppBundle:Token:token" }
