user:
    resource: '@AppBundle/Resources/config/routing/user.yml'
    prefix:   /users

event:
    resource: '@AppBundle/Resources/config/routing/event.yml'
    prefix:   /events

category:
    resource: '@AppBundle/Resources/config/routing/category.yml'
    prefix:   /categories

lecture:
    resource: '@AppBundle/Resources/config/routing/lecture.yml'
    prefix:   /lectures

form:
    resource: '@AppBundle/Resources/config/routing/form.yml'
    prefix:   /forms

registration:
    resource: '@AppBundle/Resources/config/routing/registration.yml'
    prefix:   /registrations
