AppBundle\Entity\AccessToken:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        client:
            targetEntity: AppBundle\Entity\Client
            joinColumn:
                name: clientId
                referencedColumnName: id
        user:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: userId
                referencedColumnName: id
