AppBundle\Entity\Event:
    repositoryClass: AppBundle\Doctrine\Repository\EventRepository
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: string
            length: 65535
            nullable: true
        date:
            type: datetime
            nullable: true
        place:
            type: string
            length: 255
            nullable: true
        created:
            type: datetime
    manyToOne:
        owner:
            targetEntity: AppBundle\Entity\User
            inversedBy: events
            joinColumn:
                name: userId
                referencedColumnName: id
    oneToMany:
        categories:
            targetEntity: AppBundle\Entity\Category
            mappedBy: event
