AppBundle\Entity\User:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        events:
            targetEntity: AppBundle\Entity\Event
            mappedBy: owner
